routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::get('/art', function () {


    \Illuminate\Support\Facades\Artisan::call('config:cache');
    //  \Illuminate\Support\Facades\Artisan::call('make:model',['name'=>'Join_us']);
});
Route::get('lang/{lang}', [
    "uses" => "HomeController@showLang",
    "as" => "website.lang"
]);
Route::group(['middleware' => 'lang'], function () {



    Route::group(['middleware' => 'web', 'guest'], function () {

        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/getSubcategories/{category_id}', 'admin\HomeController@getSubcategories');
        Route::get('/admin/login', 'Auth\LoginController@showLoginAdmin');

        Route::post('/loginAdmin', [
            "uses" => "Auth\LoginController@loginAdmin",
            "as" => "loginAdmin"
        ]);
        Route::post('/search_supplier', 'HomeController@search_supplier');
        Route::post('/search_prosupplier', 'HomeController@search_prosupplier');
        Route::post('/search_category', 'HomeController@search_category');
        Route::post('/searchpro_categories', 'HomeController@searchpro_categories');
        Route::post('/search_subcategory', 'HomeController@search_subcategory');
        Route::post('/search_prosubcategories', 'HomeController@search_prosubcategories');
        Route::post('/search_product', 'HomeController@search_product');
        Route::post('/share_product', 'HomeController@share_product');
        Route::post('/like_product', 'HomeController@like_product');
        Route::post('/remove_order', 'HomeController@remove_order');
        Route::post('/save_order', 'HomeController@save_order')->name('save_order');
        Route::post('/order_pro', 'HomeController@order_pro');
//tasira
        Route::post('/update_orders', 'HomeController@update_orders')->name('update_orders');
        Route::get('/detail_news/{title}', 'HomeController@detail_news')->name('website.detail_news');
        Route::get('/nnews', 'HomeController@news')->name('website.news');
        Route::get('/search_pro/{name}', 'HomeController@search_pro')->name('website.search_pro');
        Route::post('/search_news', 'HomeController@search_news');
        Route::post('/search_title', 'HomeController@search_title');
        Route::get('/supplier', 'HomeController@suppliers')->name('website.suppliers');

        Route::get('/login/{social}', 'Auth\LoginController@socialLogin')->where('social', 'twitter|facebook|google');
        Route::get('/login/{social/callback}', 'Auth\LoginController@handleprovidercallback')->where('social', 'twitter|facebook|google');
        Route::get('/contact', [
            "uses" => "HomeController@contact",
            "as" => "website.contact"
        ]);
        Route::get('/view_attach/{attachment_pro}', [
            "uses" => "HomeController@download",
            "as" => "website.viewAttach"
        ]);

        Route::get('/order_product', [
            "uses" => "HomeController@order_product",
            "as" => "website.order_product"
        ]);

        Route::get('/shopping_cart/{name}', [
            "uses" => "HomeController@shopping_cart",
            "as" => "website.shopping_cart"
        ]);

        Route::get('/product', [
            "uses" => "HomeController@getProduct",
            "as" => "website.product"
        ]);

        Route::get('/detail_product/{name}', [
            "uses" => "HomeController@detail_product",
            "as" => "website.detail_product"
        ]);
    });

    Route::group(['middleware' => ['web', 'auth'], 'perfix' => ''], function () {

        Route::get('/logout', [
            "uses" => "Auth\LoginController@logout",
            "as" => "logout"
        ]);
        Route::get('/documentaion_center', [
            "uses" => "HomeController@documentaion_center",
            "as" => "website.documentaion_center"
        ]);

        Route::get('/supplier_detail/{supplier_name}', [
            "uses" => "HomeController@supplier_detail",
            "as" => "website.detail_supplier"
        ]);
    });

    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/dashboard', [
            "uses" => "admin\HomeController@index",
            "as" => "dashboard"
        ]);
        Route::get('/category/{name}', [
            "uses" => "admin\CategoriesController@show",
            "as" => "category"
        ]);
        Route::get('/admins', [
            "uses" => "admin\UsersController@admins",
            "as" => "admins"
        ]);
        Route::get('/blocked', [
            "uses" => "admin\UsersController@blocked",
            "as" => "blocked"
        ]);
        Route::resource('/categories','admin\CategoriesController');
        Route::post('/deleteGroup/{id}', 'admin\CategoriesController@deleteGroup');
        Route::get('/admin_user/{user_id}', 'admin\UsersController@admin_user');
        Route::get('/block_user/{user_id}', 'admin\UsersController@block_user');

        Route::resource('/subcategories','admin\SubcategoriesController');
        Route::resource('/products','admin\ProductsController');
        Route::resource('/permissions','admin\PermissionsController');
        Route::resource('/suppliers', 'admin\SuppliersController');
        Route::resource('/systems', 'admin\SystemsController');
        Route::resource('/users', 'admin\UsersController');
        Route::resource('/news', 'admin\NewsController');
        Route::resource('/about_editcontent', 'admin\AboutEditContentController');
        Route::resource('/about_images', 'admin\AboutImagesController');
        Route::resource('/prize', 'admin\PrizeController');
        Route::resource('/dash_team', 'admin\DashTeamController');
        Route::resource('/employees', 'admin\EmployeesController');
        Route::get('/employeeFollowWork', 'admin\EmployeesController@efollow_work')->name('efollow_work');
        Route::get('/employeeControlSupplier', 'admin\EmployeesController@econtrol_supplier')->name('econtrol_supplier');
        Route::get('/employeeOrderProduct', 'admin\EmployeesController@eorderproduct')->name('eorderproduct');
        Route::get('/followWork/{id}', 'admin\EmployeesController@follow_work')->name('follow_work');
        Route::get('/controlSupplier/{id}', 'admin\EmployeesController@control_supplier')->name('control_supplier');
        Route::get('/receiveOrdersPro/{id}', 'admin\EmployeesController@receive_ordersPro')->name('receive_ordersPro');

    });
    Route::group(['middleware' => 'permission', 'permission' => ['visitor']], function () {

    });

    Route::group(['middleware' => 'permission', 'permission' => ['customer']], function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['suppliers']],function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['employees']],function () {

    });
    });
//add permission to role in route
Route::post('/contactUs', 'HomeController@contactUs');
Route::post('/malingList', 'HomeController@malingList');

app/Http/Controllers/admin/SubcategoriesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class SubcategoriesController extends Controller
{
    //
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sub_categories = Category::all()->where('parent_id', '!=', null);
        return view('admin.subcategories.index', compact('sub_categories'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all()->where('parent_id', null);
        return view('admin.subcategories.subcategory', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:categories',
            'en_name' => 'unique:categories|max:100|min:3',

        ]);
        $category = new Category();
        $parent_name = $request->parent_id;
        $parent = Category::find($parent_name);
        $category->name = $request->name;
        $category->en_name = $request->en_name;
        $category->parent_id = $parent_name;
        $type = $parent->type;
        $category->type = $type + 1;
        $category->save();


        return redirect('/subcategories')
            ->with('success', 'تم انشاء القسم الفرعي بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
//    public function show($name)
//    {
//        $category = Category::where('name',$name)->first();
//
//        $sub_categories = Category::where('parent_id', $category->id)->get();
//
//        return view('admin.categories.subcategory_index', compact('category', 'sub_categories'));
//    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sub_category = Category::find($id);
        $categories = Category::all()->where('parent_id', null);

        return view('admin.subcategories.subcategory', compact('sub_category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'unique:categories',
            'en_name' => 'unique:categories|max:100|min:3',

        ]);
        $subcategory = Category::find($id);
        $subcategory->name = $request->name;
        $subcategory->en_name = $request->en_name;
        $parent_name = $request->parent_id;
        $subcategory->parent_id = $parent_name;
        $parent = Category::find($parent_name);
        $type = $parent->type;
        $subcategory->type = $type + 1;
        $subcategory->save();

        return redirect('/subcategories')
            ->with('success', 'تم تعديل القسم الفرعي بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategory = Category::find($id);
        $subcategory->delete();
        return response()->json(['success' => 'true']);
    }
}

resources/views/admin/subcategories/index.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('dashboard')}}"><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    {{trans('local.subcategories')}}
                </div>
            </div>
        </div>
    </div>
    @include('admin.alert')

    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title text-center col-12 wow fadeIn">{{trans('local.hello_in').trans('local.subcategories')." "}}</h3>

            <div class="category-table wow fadeIn col-12">

                <table id="example" class="table datatable-save-state table-striped table-bordered table-responsive-sm">
                    <thead>
                    <tr>
                        <th>#{{trans('local.ID')}}</th>
                        <th>{{trans('local.name_category')}}</th>
                        <th> {{trans('local.category_en')}}</th>
                        <th> {{trans('local.category_related')}}</th>
                        <th>{{trans('local.date_created')}} </th>
                        <th> {{trans('local.action_taken')}}</th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=1?>
                    @foreach($sub_categories as $sub_category)
                        <tr>
                            <td>{{$i++}}</td>
                            <td><a href="{{route('category',$sub_category->name)}}" style="color: blue;">{{$sub_category->name}}</a></td>
                            <td>{{$sub_category->en_name}}</td>
                            <td>{{$sub_category->parentCategory->name}}</td>
                            <td>{{$sub_category->created_at->format("d/m/Y")}}</td>
                            <td>
                                <a href="{{route('subcategories.edit',$sub_category->id)}}" class="edit-btn-table"><i class="fa fa-pencil"></i></a>


                                {{--<button class="edit-btn-table remove-btn sweet-2" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-2']);"><i class="fa fa-times"></i> </button>--}}
                                <a  title="حذف القسم" onclick="return false;" object_id="{{ $sub_category->id }}"
                                    delete_url="/subcategories/" class="edit-btn-table remove-btn sweet_warning" href="#">
                                    <i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    @endforeach


                    </tbody>
                </table>

            </div>
            <div class="col-12 left-btn">
                <a href="{{route('subcategories.create')}}" class="custom_btn dark_btn">{{trans('local.add_subcategory')}}</a>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/subcategories/subcategory.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('dashboard')}}"><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    <a href="{{route('categories.index')}}">{{trans('local.categories')}}</a>
                    {{isset($sub_category)?trans('local.edit_subcategory'):trans('local.add_subcategory')}}
                </div>
            </div>
        </div>
    </div>
    @if (isset($errors))
        <div id="sweet_warning" style="display: none" class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br/>
            @endforeach
        </div>
    @endif
    @include('admin.alert')
    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title col-12 wow fadeIn"><i class="fa fa-plus"></i>{{trans('local.hello_in')}} <span class="dash-title-span">{{isset($sub_category)?trans('local.edit_subcategory'):trans('local.add_subcategory')}}
</span></h3>


            <div class="about-text-div col-12 margin-div2">
                <div class="container">
                    <form class="needs-validation row" method="post" enctype="multipart/form-data" action="{{ isset($sub_category)? route('subcategories.update',$sub_category->id):route('subcategories.store')}}" novalidate>
                        {!! csrf_field() !!}
                        @if(isset($sub_category))
                            <input type="hidden" name="_method" value="PATCH" />
                        @endif

                        <div class="form-group col-md-6">
                            <label>{{trans('local.chooseMain_category')}}</label>
                            <select name="parent_id" class="form-control" required>
                                <option>{{trans('local.chooseMain_category')}}</option>

                            @foreach($categories as $category)
                                <option value="{{$category->id}}"{{isset($sub_category)&&$sub_category->parentCategory->name == $category->name?'selected':''}}>{{$category->name}}</option>
                               @endforeach
                            </select>
                            <div class="invalid-feedback">
                                من فضلك أدخل نص صحيح
                            </div>
                        </div>

                        <div class="form-group col-12">
                            <label>{{trans('local.input_subcategory')}}</label>
                            <input type="text" class="form-control" value="{{isset($sub_category)?$sub_category->name:''}}" name="name" required>
                            <div class="invalid-feedback">
                                من فضلك أدخل نص صحيح
                            </div>
                        </div>

                        <div class="form-group col-12">
                            <label>{{trans('local.input_subcategoryEn')}} </label>
                            <input type="text" class="form-control" value="{{isset($sub_category)?$sub_category->en_name:''}}" name="en_name" required>
                            <div class="invalid-feedback">
                                من فضلك أدخل نص صحيح
                            </div>
                        </div>


                        <div class="left-btn col-12">
                            <button type="submit" class="custom_btn dark-btn"> {{isset($sub_category)?trans('local.edit'):trans('local.save')}}</button>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection