routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::get('/art', function () {


    \Illuminate\Support\Facades\Artisan::call('config:cache');
    //  \Illuminate\Support\Facades\Artisan::call('make:model',['name'=>'Join_us']);
});
Route::get('lang/{lang}', [
    "uses" => "HomeController@showLang",
    "as" => "website.lang"
]);
Route::group(['middleware' => 'lang'], function () {



    Route::group(['middleware' => 'web', 'guest'], function () {

        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/getSubcategories/{category_id}', 'admin\HomeController@getSubcategories');
        Route::get('/admin/login', 'Auth\LoginController@showLoginAdmin');

        Route::post('/loginAdmin', [
            "uses" => "Auth\LoginController@loginAdmin",
            "as" => "loginAdmin"
        ]);
        Route::post('/search_supplier', 'HomeController@search_supplier');
        Route::post('/search_prosupplier', 'HomeController@search_prosupplier');
        Route::post('/search_category', 'HomeController@search_category');
        Route::post('/searchpro_categories', 'HomeController@searchpro_categories');
        Route::post('/search_subcategory', 'HomeController@search_subcategory');
        Route::post('/search_prosubcategories', 'HomeController@search_prosubcategories');
        Route::post('/search_product', 'HomeController@search_product');
        Route::post('/share_product', 'HomeController@share_product');
        Route::post('/like_product', 'HomeController@like_product');
        Route::post('/remove_order', 'HomeController@remove_order');
        Route::post('/save_order', 'HomeController@save_order')->name('save_order');
        Route::post('/order_pro', 'HomeController@order_pro');
//tasira
        Route::post('/update_orders', 'HomeController@update_orders')->name('update_orders');
        Route::get('/detail_news/{title}', 'HomeController@detail_news')->name('website.detail_news');
        Route::get('/nnews', 'HomeController@news')->name('website.news');
        Route::get('/search_pro/{name}', 'HomeController@search_pro')->name('website.search_pro');
        Route::post('/search_news', 'HomeController@search_news');
        Route::post('/search_title', 'HomeController@search_title');
        Route::get('/supplier', 'HomeController@suppliers')->name('website.suppliers');

        Route::get('/login/{social}', 'Auth\LoginController@socialLogin')->where('social', 'twitter|facebook|google');
        Route::get('/login/{social/callback}', 'Auth\LoginController@handleprovidercallback')->where('social', 'twitter|facebook|google');
        Route::get('/contact', [
            "uses" => "HomeController@contact",
            "as" => "website.contact"
        ]);
        Route::get('/view_attach/{attachment_pro}', [
            "uses" => "HomeController@download",
            "as" => "website.viewAttach"
        ]);

        Route::get('/order_product', [
            "uses" => "HomeController@order_product",
            "as" => "website.order_product"
        ]);

        Route::get('/shopping_cart/{name}', [
            "uses" => "HomeController@shopping_cart",
            "as" => "website.shopping_cart"
        ]);

        Route::get('/product', [
            "uses" => "HomeController@getProduct",
            "as" => "website.product"
        ]);

        Route::get('/detail_product/{name}', [
            "uses" => "HomeController@detail_product",
            "as" => "website.detail_product"
        ]);
    });

    Route::group(['middleware' => ['web', 'auth'], 'perfix' => ''], function () {

        Route::get('/logout', [
            "uses" => "Auth\LoginController@logout",
            "as" => "logout"
        ]);
        Route::get('/documentaion_center', [
            "uses" => "HomeController@documentaion_center",
            "as" => "website.documentaion_center"
        ]);

        Route::get('/supplier_detail/{supplier_name}', [
            "uses" => "HomeController@supplier_detail",
            "as" => "website.detail_supplier"
        ]);
    });

    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/dashboard', [
            "uses" => "admin\HomeController@index",
            "as" => "dashboard"
        ]);
        Route::get('/category/{name}', [
            "uses" => "admin\CategoriesController@show",
            "as" => "category"
        ]);
        Route::get('/admins', [
            "uses" => "admin\UsersController@admins",
            "as" => "admins"
        ]);
        Route::get('/blocked', [
            "uses" => "admin\UsersController@blocked",
            "as" => "blocked"
        ]);
        Route::resource('/categories','admin\CategoriesController');
        Route::post('/deleteGroup/{id}', 'admin\CategoriesController@deleteGroup');
        Route::get('/admin_user/{user_id}', 'admin\UsersController@admin_user');
        Route::get('/block_user/{user_id}', 'admin\UsersController@block_user');

        Route::resource('/subcategories','admin\SubcategoriesController');
        Route::resource('/products','admin\ProductsController');
        Route::resource('/permissions','admin\PermissionsController');
        Route::resource('/suppliers', 'admin\SuppliersController');
        Route::resource('/systems', 'admin\SystemsController');
        Route::resource('/users', 'admin\UsersController');
        Route::resource('/news', 'admin\NewsController');
        Route::resource('/about_editcontent', 'admin\AboutEditContentController');
        Route::resource('/about_images', 'admin\AboutImagesController');
        Route::resource('/prize', 'admin\PrizeController');
        Route::resource('/dash_team', 'admin\DashTeamController');
        Route::resource('/employees', 'admin\EmployeesController');
        Route::get('/employeeFollowWork', 'admin\EmployeesController@efollow_work')->name('efollow_work');
        Route::get('/employeeControlSupplier', 'admin\EmployeesController@econtrol_supplier')->name('econtrol_supplier');
        Route::get('/employeeOrderProduct', 'admin\EmployeesController@eorderproduct')->name('eorderproduct');
        Route::get('/followWork/{id}', 'admin\EmployeesController@follow_work')->name('follow_work');
        Route::get('/controlSupplier/{id}', 'admin\EmployeesController@control_supplier')->name('control_supplier');
        Route::get('/receiveOrdersPro/{id}', 'admin\EmployeesController@receive_ordersPro')->name('receive_ordersPro');

    });
    Route::group(['middleware' => 'permission', 'permission' => ['visitor']], function () {

    });

    Route::group(['middleware' => 'permission', 'permission' => ['customer']], function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['suppliers']],function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['employees']],function () {

    });
    });
//add permission to role in route
Route::post('/contactUs', 'HomeController@contactUs');
Route::post('/malingList', 'HomeController@malingList');

resources/views/admin/prize_certificates/index.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('dashboard')}}"><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    {{trans('local.company_awards')}}
                </div>
            </div>
        </div>
    </div>
    @include('admin.alert')

    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title text-center col-12 wow fadeIn">{{trans('local.hello_in')}}<span class="dash-title-span">{{trans('local.company_awards')}}</span></h3>

            <div class="category-table wow fadeIn col-12">
                <table id="example" class="table datatable-save-state table-striped table-bordered table-responsive-sm">
                    <thead>
                    <tr>
                        <th>#{{trans('local.ID')}}</th>
                        <th> {{trans('local.about_image')}}</th>
                        <th>{{trans('local.date_created')}} </th>
                        <th> {{trans('local.action_taken')}}</th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=1?>
                    @foreach($certificates as $certificate)
                        <tr>
                            <td>{{$i++}}</td>
                            <td><img src="{{asset('uploads/'.$certificate->image)}}" class="t-pro-img"
                                     alt="img"/> </td>
                            <td>{{$certificate->created_at->format("d/m/Y")}}</td>
                            <td>
                                <a href="{{route('prize.edit',$certificate->id)}}" class="edit-btn-table"><i class="fa fa-pencil"></i></a>
                                <a title="حذف الصوره " onclick="return false;" object_id="{{ $certificate->id }}"
                                   delete_url="/prize/" class="edit-btn-table remove-btn sweet_warning" href="#">
                                    <i class="fa fa-times"></i></a>

                            </td>
                        </tr>
                    @endforeach


                    </tbody>
                </table>

            </div>
            <div class="col-12 left-btn">
                <a href="{{route('prize.create')}}" class="custom_btn dark_btn">{{trans('local.add_imagePrize')}}</a>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/prize_certificates/prize_certificate.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('dashboard')}}"><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    <a href="{{route('prize.index')}}">{{trans('local.insert_photos')}}</a>
                    {{isset($prize)?trans('local.edit_photo'):trans('local.add_photo')}}
                </div>
            </div>
        </div>
    </div>
    @if (isset($errors))
        <div id="sweet_warning" style="display: none" class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br/>
            @endforeach
        </div>
    @endif
    @include('admin.alert')
    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title col-12 wow fadeIn"><i class="fa fa-plus"></i>{{trans('local.hello_in')}} <span
                        class="dash-title-span">{{isset($prize)?trans('local.edit_photo'):trans('local.add_photo')}}
            </span></h3>


            <div class="about-text-div col-12 margin-div2">
                <div class="container">
                    <form class="needs-validation row" method="post" enctype="multipart/form-data"
                          action="{{ isset($prize)? route('prize.update',$prize->id):route('prize.store')}}"
                          novalidate>
                        {!! csrf_field() !!}
                        @if(isset($prize))
                            <input type="hidden" name="_method" value="PATCH"/>
                        @endif



                        <div class="form-group col-12">
                            <label>{{trans('local.add_photo')}}</label>
                            <input type="file" name="image" id="chooseFile"
                                   value="{{isset($prize)?$prize->image:''}}" onchange="readURL(this);"
                                   class="form-control" {{isset($prize)?:'required'}}>
                            <div class="invalid-feedback">
                                من فضلك أدخل ملف صحيح
                            </div>
                        </div>
                        <hr>

                        <div class="form-group col-12">
                            <img width="150" height="100px" class="thumb-preview" id="blah" style="margin: auto auto 10px;
                    display: block;" align="center" src="{{isset($prize)?asset('/uploads/'.$prize->image):''}}"
                                 alt=""/>

                        </div>






                        <div class="left-btn col-12">
                            <button type="submit"
                                    class="custom_btn dark-btn"> {{isset($prize)?trans('local.edit'):trans('local.save')}}</button>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection