routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::get('/art', function () {


    \Illuminate\Support\Facades\Artisan::call('config:cache');
    //  \Illuminate\Support\Facades\Artisan::call('make:model',['name'=>'Join_us']);
});
Route::get('lang/{lang}', [
    "uses" => "HomeController@showLang",
    "as" => "website.lang"
]);
Route::group(['middleware' => 'lang'], function () {



    Route::group(['middleware' => 'web', 'guest'], function () {

        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/getSubcategories/{category_id}', 'admin\HomeController@getSubcategories');
        Route::get('/admin/login', 'Auth\LoginController@showLoginAdmin');

        Route::post('/loginAdmin', [
            "uses" => "Auth\LoginController@loginAdmin",
            "as" => "loginAdmin"
        ]);
        Route::post('/search_supplier', 'HomeController@search_supplier');
        Route::post('/search_prosupplier', 'HomeController@search_prosupplier');
        Route::post('/search_category', 'HomeController@search_category');
        Route::post('/searchpro_categories', 'HomeController@searchpro_categories');
        Route::post('/search_subcategory', 'HomeController@search_subcategory');
        Route::post('/search_prosubcategories', 'HomeController@search_prosubcategories');
        Route::post('/search_product', 'HomeController@search_product');
        Route::post('/share_product', 'HomeController@share_product');
        Route::post('/like_product', 'HomeController@like_product');
        Route::post('/remove_order', 'HomeController@remove_order');
        Route::post('/save_order', 'HomeController@save_order')->name('save_order');
        Route::post('/order_pro', 'HomeController@order_pro');
//tasira
        Route::post('/update_orders', 'HomeController@update_orders')->name('update_orders');
        Route::get('/detail_news/{title}', 'HomeController@detail_news')->name('website.detail_news');
        Route::get('/nnews', 'HomeController@news')->name('website.news');
        Route::get('/search_pro/{name}', 'HomeController@search_pro')->name('website.search_pro');
        Route::post('/search_news', 'HomeController@search_news');
        Route::post('/search_title', 'HomeController@search_title');
        Route::get('/supplier', 'HomeController@suppliers')->name('website.suppliers');

        Route::get('/login/{social}', 'Auth\LoginController@socialLogin')->where('social', 'twitter|facebook|google');
        Route::get('/login/{social/callback}', 'Auth\LoginController@handleprovidercallback')->where('social', 'twitter|facebook|google');
        Route::get('/contact', [
            "uses" => "HomeController@contact",
            "as" => "website.contact"
        ]);
        Route::get('/view_attach/{attachment_pro}', [
            "uses" => "HomeController@download",
            "as" => "website.viewAttach"
        ]);

        Route::get('/order_product', [
            "uses" => "HomeController@order_product",
            "as" => "website.order_product"
        ]);

        Route::get('/shopping_cart/{name}', [
            "uses" => "HomeController@shopping_cart",
            "as" => "website.shopping_cart"
        ]);

        Route::get('/product', [
            "uses" => "HomeController@getProduct",
            "as" => "website.product"
        ]);

        Route::get('/detail_product/{name}', [
            "uses" => "HomeController@detail_product",
            "as" => "website.detail_product"
        ]);
    });

    Route::group(['middleware' => ['web', 'auth'], 'perfix' => ''], function () {

        Route::get('/logout', [
            "uses" => "Auth\LoginController@logout",
            "as" => "logout"
        ]);
        Route::get('/documentaion_center', [
            "uses" => "HomeController@documentaion_center",
            "as" => "website.documentaion_center"
        ]);

        Route::get('/supplier_detail/{supplier_name}', [
            "uses" => "HomeController@supplier_detail",
            "as" => "website.detail_supplier"
        ]);
    });

    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/dashboard', [
            "uses" => "admin\HomeController@index",
            "as" => "dashboard"
        ]);
        Route::get('/category/{name}', [
            "uses" => "admin\CategoriesController@show",
            "as" => "category"
        ]);
        Route::get('/admins', [
            "uses" => "admin\UsersController@admins",
            "as" => "admins"
        ]);
        Route::get('/blocked', [
            "uses" => "admin\UsersController@blocked",
            "as" => "blocked"
        ]);
        Route::resource('/categories','admin\CategoriesController');
        Route::post('/deleteGroup/{id}', 'admin\CategoriesController@deleteGroup');
        Route::get('/admin_user/{user_id}', 'admin\UsersController@admin_user');
        Route::get('/block_user/{user_id}', 'admin\UsersController@block_user');

        Route::resource('/subcategories','admin\SubcategoriesController');
        Route::resource('/products','admin\ProductsController');
        Route::resource('/permissions','admin\PermissionsController');
        Route::resource('/suppliers', 'admin\SuppliersController');
        Route::resource('/systems', 'admin\SystemsController');
        Route::resource('/users', 'admin\UsersController');
        Route::resource('/news', 'admin\NewsController');
        Route::resource('/about_editcontent', 'admin\AboutEditContentController');
        Route::resource('/about_images', 'admin\AboutImagesController');
        Route::resource('/prize', 'admin\PrizeController');
        Route::resource('/dash_team', 'admin\DashTeamController');
        Route::resource('/employees', 'admin\EmployeesController');
        Route::get('/employeeFollowWork', 'admin\EmployeesController@efollow_work')->name('efollow_work');
        Route::get('/employeeControlSupplier', 'admin\EmployeesController@econtrol_supplier')->name('econtrol_supplier');
        Route::get('/employeeOrderProduct', 'admin\EmployeesController@eorderproduct')->name('eorderproduct');
        Route::get('/followWork/{id}', 'admin\EmployeesController@follow_work')->name('follow_work');
        Route::get('/controlSupplier/{id}', 'admin\EmployeesController@control_supplier')->name('control_supplier');
        Route::get('/receiveOrdersPro/{id}', 'admin\EmployeesController@receive_ordersPro')->name('receive_ordersPro');

    });
    Route::group(['middleware' => 'permission', 'permission' => ['visitor']], function () {

    });

    Route::group(['middleware' => 'permission', 'permission' => ['customer']], function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['suppliers']],function () {

    });

    Route::group(['middleware'=>'permission','permission'=>['employees']],function () {

    });
    });
//add permission to role in route
Route::post('/contactUs', 'HomeController@contactUs');
Route::post('/malingList', 'HomeController@malingList');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = 'categories';
    protected $fillable = [
        'id', 'name', 'en_name', 'type', 'parent_id',
    ];

    public function subCategory()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function attributes()
    {
        return $this->hasMany(Attribute::class, 'category_id', 'id');
    }

    public function getProduct()
    {
        return $this->hasMany(Products::class, 'category_id', 'id');
    }
}

app/Http/Controllers/admin/CategoriesController.php
<?php

namespace App\Http\Controllers\admin;



use App\Http\Controllers\Controller;
use App\Models\Attribute;
use App\Models\Category;
use App\Models\Product_attribute;
use Illuminate\Http\Request;


class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all()->where('parent_id', null);
            return view('admin.categories.index', compact('categories'));

    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */

    public function deleteGroup($id)
    {

        $attribute = Attribute::find($id);
        if ($attribute->group_id == null) {
            foreach ($attribute->attributes as $item) {
                //remove attribute from products
                Product_attribute::where('attribute_id', $item->id)->delete();
                //delete attribute
                $item->delete();

            }

            $attribute->delete();
            return response()->json(['success' => 'true']);

        } else {
            //remove attribute from products
            Product_attribute::where('attribute_id', $id)->delete();
        }
        $attribute->delete();
        return response()->json(['success' => 'true']);

    }
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|unique:categories',
            'en_name' => 'unique:categories|max:100|min:3',

        ]);
        $data = $request->all();
        $groups = $data['group'];



        $category = new Category();
        $category->name = $request->name;
        $category->en_name = $request->en_name;
        $category->type = 1;
        $file = $request->file('icon_cat');
        if ($request->hasFile('icon_cat')) {
            $fileName = 'icon_cat-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
            $destinationPath = 'uploads';
            $request->file('icon_cat')->move($destinationPath, $fileName);
            $category->icon_cat = $fileName;
        }
        $category->save();


        $attribute_id = Attribute::create([
            "category_id" => $category['id'],
            "name" => 1,
            "group_id" => null
        ]);
        foreach ($groups as $group) {


            if (array_key_exists('attribute_key', $group)) {

                $attributeKeys = $group['attribute_key'];

                if (!empty($attributeKeys)) {

                    $attributes = Attribute::create([
                        "category_id" => $category['id'],
                        "name" => $attributeKeys[0],
                        "group_id" => $attribute_id['id']
                    ]);
                    $attribute = Attribute::find($attributes->id);
                    $attribute->en_name = $attributeKeys[1];
                    $attribute->save();
                }
            }

        }

        return redirect('/categories')
            ->with('success', 'تم انشاء القسم بنجاح');


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($name)
    {
        $category = Category::where('name',$name)->first();

        $sub_categories = Category::where('parent_id', $category->id)->get();

        return view('admin.categories.subcategory_index', compact('category', 'sub_categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::where('id', $id)->with('attributes')->first();
        return view('admin.categories.category', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */


    public function update(Request $request, $id)
    {
        $data = $request->all();
        $this->validate($request, [
            'name' => '',
            'en_name' => 'max:100|min:3',

        ]);
        $groups = $data['group'];
        $category = Category::find($id);
        $category->name = $request->name;
        $category->en_name = $request->en_name;
        $category->type = 1;
        $file = $request->file('icon_cat');
        if ($request->hasFile('icon_cat')) {
            $old_file = 'uploads/' . $category->image;
            if (is_file($old_file)) unlink($old_file);
            $fileName = 'icon_cat-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
            $destinationPath = 'uploads';
            $request->file('icon_cat')->move($destinationPath, $fileName);
            $category->icon_cat = $fileName;
        }
        $category->save();


        $oldgroups = Attribute::where('category_id', $category['id'])->where('group_id', null)->with('attributes')->first();
//
        foreach ($groups as $group) {


            if (array_key_exists('attribute_key', $group)) {

                $attributeKeys = $group['attribute_key'];

                if (!empty($attributeKeys)) {

                    $attributes = Attribute::create([
                        "category_id" => $category['id'],
                        "name" => $attributeKeys[0],
                        "group_id" => $oldgroups->id
                    ]);
                    $attribute = Attribute::find($attributes->id);
                    $attribute->en_name = $attributeKeys[1];
                    $attribute->save();
                }
            }

        }




        return redirect('/categories')
            ->with('success', 'تم تعديل القسم بنجاح');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        $attributes = Attribute::where('category_id', $category->id)->get();
        foreach ($attributes as $attribute) {
            $attribute->delete();
        }
        return response()->json(['success'=>'true']);
    }
}

resources/views/admin/categories/category.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('dashboard')}}"><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    <a href="{{route('categories.index')}}">{{trans('local.categories')}}</a>
                    {{isset($category)?trans('local.edit_category'):trans('local.add_category')}}
                </div>
            </div>
        </div>
    </div>
    @if (isset($errors))
        <div id="sweet_warning" style="display: none" class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br/>
            @endforeach
        </div>
    @endif
    @include('admin.alert')
    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title col-12 wow fadeIn"><i class="fa fa-plus"></i>{{trans('local.hello_in')}} <span class="dash-title-span">{{isset($category)?trans('local.edit_category'):trans('local.add_category')}}
</span></h3>


            <div class="about-text-div col-12 margin-div2">
                <div class="container">
                    <form class="needs-validation row" method="post" enctype="multipart/form-data" action="{{ isset($category)? route('categories.update',$category->id):route('categories.store')}}" novalidate>
                        {!! csrf_field() !!}
                        @if(isset($category))
                            <input type="hidden" name="_method" value="PATCH" />
                        @endif

                        <div class="form-group col-12">
                            <label>{{trans('local.input_maincategory')}}</label>
                            <input type="text" class="form-control" value="{{isset($category)?$category->name:''}}" name="name" required>
                            <div class="invalid-feedback">
                                من فضلك أدخل نص صحيح
                            </div>
                        </div>

                        <div class="form-group col-12">
                            <label>{{trans('local.input_maincategoryEn')}} </label>
                            <input type="text" class="form-control" value="{{isset($category)?$category->en_name:''}}" name="en_name" required>
                            <div class="invalid-feedback">
                                من فضلك أدخل نص صحيح
                            </div>
                        </div>


                        <div class="form-group col-12">
                            <label>{{trans('local.icon_cat')}}</label>
                            <input type="file" name="icon_cat" id="chooseFile"
                                   value="{{isset($category)?$category->icon_cat:''}}" onchange="readURL(this);"
                                   class="form-control" {{isset($category)?:'required'}}>
                            <div class="invalid-feedback">
                                من فضلك أدخل ملف صحيح
                            </div>
                        </div>
                        <hr>

                        <div class="form-group col-12">
                            <img width="150" height="100px" class="thumb-preview" id="blah" style="margin: auto auto 10px;
                    display: block;" align="center" src="{{isset($category)?asset('/uploads/'.$category->icon_cat):''}}"
                                 alt=""/>

                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-3">{{trans('local.descr')}}</label>
                            @if(isset($category))

                                    @if($category->attributes()->where('group_id', null)->count())
                                        @foreach($category->attributes()->where("group_id", null)->get() as $key => $group)
                                        <div class="col-12 row form-group itemsGroupsContainer">

                                            <div class="itemsContainer"
                                                 style="margin-top:5px; padding:5px; border:1px solid #eee">

                                                {{--<div class=" form-group col-md-6">--}}
                                                {{--<input type="hidden" name="group[4][attribute]"--}}
                                                {{--value="{{ $group->name }}"--}}
                                                {{--class="form-control" data-key="{{ $key }}"--}}
                                                {{--placeholder="المجموعه">--}}
                                                {{--</div>--}}

                                                {{--<div class=" form-group col-md-6">--}}
                                                {{--<input type="hidden" name="group[4][attribute_key]"--}}
                                                {{--value="[]"--}}
                                                {{--class="form-control" data-key="{{ $key }}"--}}
                                                {{--placeholder="المجموعه">--}}
                                                {{--</div>--}}
                                                {{--<div class=" form-group col-md-6">--}}
                                                {{--<input type="hidden" name="group[4][group_id]"--}}
                                                {{--value="{{4}}">--}}

                                                {{--</div>--}}

                                                @foreach($category->attributes->where("group_id", $group->id) as $attribute_key => $attribute_value)


                                                    <div class="col-12 row form-group" id="itemsContainer"
                                                         style="margin-top:5px">
                                                        <div class="form-group col-md-6">

                                                            <input type="text"
                                                                   name="group[4][attribute_key][{{ $attribute_key+1 }}]"
                                                                   value="{{ $attribute_value->name }}"
                                                                   class="form-control text"
                                                                   placeholder="{{trans('local.descr')}}" disabled>
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <input type="text"
                                                                   name="group[4][attribute_key][{{ $attribute_key+2}}]"
                                                                   value="{{ $attribute_value->en_name }}"
                                                                   class="form-control key"
                                                                   placeholder="{{trans('local.descr_en')}}" disabled>
                                                        </div>
                                                        <div class="col-md-4">
                                                            <a class="btn btn-danger btn-xs destroyItem"
                                                               onclick="return false;"
                                                               object_id="{{ $attribute_value->id }}"
                                                               delete_url="/deleteGroup/{{ $attribute_value->id }}"><i
                                                                        class="fa fa-times"></i></a>
                                                        </div>

                                                    </div>


                                                @endforeach


                                            </div>
                                        </div>
                                        @endforeach
                                    <div class="col-12 row form-group itemsGroupsContainer">

                                        <div class="itemsContainer">
                                            <div class=" form-group col-md-6">
                                                <input type="hidden" name="group[0][group_id]" class="group_id"
                                                       value="{{ $group->id }}">
                                                <input type="hidden" name="group[0][attribute]" value="edit"
                                                       class="form-control attribute" data-key="0"
                                                       placeholder="المجموعه">

                                            </div>


                                            <div class="col-lg-12 row form-group" style="margin-top:5px">
                                                <div class="form-group col-md-6">
                                                    <input type="text" name="group[0][attribute_key][0]" value=""
                                                           class="form-control text"
                                                           placeholder="{{trans('local.descr')}}">
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input type="text" name="group[0][attribute_key][1]" value=""
                                                           class="form-control key"
                                                           placeholder="{{trans('local.descr_en')}}">
                                                </div>
                                            </div>


                                        </div>
                                        <div class="form-group col-md-6 ">
                                            <span class="custom_btn dark_btn addItemsGroup"><i class="fa fa-plus"></i>إضافة أخري</span>
                                        </div>
                                    </div>


                                @endif




                            @else

                                <div class="col-12 row form-group itemsGroupsContainer">
                                    <div class="itemsContainer">
                                        <div class=" form-group col-md-6">
                                            <input type="hidden" name="group[0][attribute]" value=""
                                                   class="form-control" data-key="0" placeholder="المجموعه">
                                        </div>



                                        <div class="col-12 row form-group" style="margin-top:5px">
                                            <div class="form-group col-md-6">
                                                <input type="text" name="group[0][attribute_key][0]" value=""
                                                       class="form-control text" placeholder="{{trans('local.descr')}}">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <input type="text" name="group[0][attribute_key][1]" value=""
                                                       class="form-control key"
                                                       placeholder="{{trans('local.descr_en')}}">
                                            </div>
                                        </div>


                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <span class="custom_btn dark_btn addItemsGroup"><i class="fa fa-plus"></i>إضافة أخري</span>
                                    </div>
                                </div>




                            @endif
                        </div>




                        <div class="left-btn col-12">
                            <button type="submit" class="custom_btn dark-btn"> {{isset($category)?trans('local.edit'):trans('local.save')}}</button>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
    @endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.layout')
@section('content_dashboard')
    <div class="dash-breadcrumbes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href=""><i class="fa fa-home"></i>{{trans('local.index')}}</a>
                    {{trans('local.main_categories')}}
                </div>
            </div>
        </div>
    </div>
    @include('admin.alert')

    <!--end dash-breadcrumbes-->
    <div class="container">
        <div class="row">

            <h3 class="dash-main-title text-center col-12 wow fadeIn">{{trans('local.hello_in')}}<span class="dash-title-span">{{trans('local.categories')}}</span></h3>

            <div class="category-table wow fadeIn col-12">
                <table id="example" class="table datatable-save-state table-striped table-bordered table-responsive-sm">
                    <thead>
                    <tr>
                        <th>#{{trans('local.ID')}}</th>
                        <th>{{trans('local.name_category')}}</th>
                        <th> {{trans('local.category_en')}}</th>
                        <th>{{trans('local.date_created')}} </th>
                        <th> {{trans('local.action_taken')}}</th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=1?>
                    @foreach($categories as $category)
                    <tr>
                        <td>{{$i++}}</td>
                        <td><a href="{{route('category',$category->name)}}" style="color: blue;">{{$category->name}}</a></td>
                        <td>{{$category->en_name}}</td>
                        <td>{{$category->created_at->format("d/m/Y")}}</td>
                        <td>
                            <a href="{{route('categories.edit',$category->id)}}" class="edit-btn-table"><i class="fa fa-pencil"></i></a>


                            {{--<button class="edit-btn-table remove-btn sweet-2" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-2']);"><i class="fa fa-times"></i> </button>--}}
                            <a  title="حذف القسم" onclick="return false;" object_id="{{ $category->id }}"
                                delete_url="/categories/" class="edit-btn-table remove-btn sweet_warning" href="#">
                                <i class="fa fa-times"></i></a>
                        </td>
                    </tr>
@endforeach


                    </tbody>
                </table>

            </div>
            <div class="col-12 left-btn">
                <a href="{{route('categories.create')}}" class="custom_btn dark_btn">{{trans('local.add_category')}}</a>
            </div>

        </div>
    </div>
    @endsection